### ISSUE TITLE
viết user stories

### ISSUE THREAD

**Issue by hieu7404** [fluoxetinedrx/Text-Summary#24]

**Comment by UETER2226** [comment]
Một user story là một phương tiện giải thích không chính thức và tổng quan về một tính năng của phần mềm, được viết từ góc nhìn của người dùng cuối hoặc khách hàng
Dưới đây là một số user story cho dự án của  chúng tôi
- Là một người dùng thường xuyên đọc các bài báo và tài liệu dài, tôi muốn có khả năng tải lên một tài liệu và nhận được bản tóm tắt ngắn gọn , để tiết kiệm thời gian và hiểu được nội dung chính mà không cần đọc toàn bộ tài liệu
- Là một người dùng cần tóm tắt với độ dài khác nhau tùy thuộc vào mục đích sử dụng, tôi muốn có thể chọn độ dài của bản tóm tắt từ ngắn gọn đến chi tiết, để đáp ứng nhu cầu cụ thể cho từng tình huống sử dụng khác nhau
- Là một người dùng nghiên cứu, tôi muốn có khả năng lưu trữ và quản lý các bản tóm tắt đã tạo, để dễ dàng truy cập và sử dụng lại trong tương lai
- Là một người dùng nghiên cứu, tôi muốn có thể tóm tắt văn bản từ nhiều nguồn khác nhau như trang web, PDF, và tài liệu văn bản, để thuận tiện trong việc thu thập và phân tích thông tin từ nhiều nguồn
